function dataToSubmit(formData) {
	return {
		vehicule: {
			yearDateMEC: formData['yearDateMEC'],
			dateMEC: formData['dateMEC'],
			marque: formData['marque'],
			model: formData['model'],
			alimentation: formData['alimentation'],
			chevaux: formData['chevaux'],
			carrosserie: formData['carrosserie'],
			version: formData['version'],
			codeGta: formData['codeGta'],
			stationnement: formData['stationnement'],
			usage: formData['usage'],
			codePostalPro: formData['codePostalPro'],
			kilometrage: formData['kilometrage'],
			financement: formData['financement'],
			remorque: formData['remorque'],
			isActuellementAssure: formData['isActuellementAssure'],
			isVehiculeAmenagePMR: formData['isVehiculeAmenagePMR'],
		},
		conducteurPrincipal: {
			isConduiteMaroc: formData['isConduiteMaroc'],
			isConduiteTunisie: formData['isConduiteTunisie'],
			isConduiteTurquie: formData['isConduiteTurquie'],
			isConduiteRussie: formData['isConduiteRussie'],
			antecedents: {
				bonusMalus: formData['bonusMalus'],
				isEteAssure36DerniersMois: formData['isEteAssure36DerniersMois'],
				dateResiliation36DerniersMois: formData['dateResiliation36DerniersMois'],
				isAssure36DerniersMoisAvec9MoisConsecutifs: formData['isAssure36DerniersMoisAvec9MoisConsecutifs'],
				nbrAnneeBonusCinquante: formData['nbrAnneeBonusCinquante'],
				periodeAssure36DerniersMois: formData['periodeAssure36DerniersMois'],
				motifResiliation36DerniersMois: formData['motifResiliation36DerniersMois'],
				dureeNonPaiement: formData['dureeNonPaiement'],
				nombreAssureursResiliationNonPaiement: formData['nombreAssureursResiliationNonPaiement'],
				recidiveResiliationNonPaiement: formData['recidiveResiliationNonPaiement'],
				contentieuxSoldeResiliationNonPaiement: formData['contentieuxSoldeResiliationNonPaiement'],
				isEuSinistres36DerniersMois: formData['isEuSinistres36DerniersMois'],
				isEuAlcoolemie36DerniersMois: formData['isEuAlcoolemie36DerniersMois'],
				isEuStupefiant36DerniersMois: formData['isEuStupefiant36DerniersMois'],
				isEteResilie36DerniersMois: formData['isEteResilie36DerniersMois'],
				alcoolemie: {
					sanction: {
						dateInitialPermisApresAnnulation: formData['dateInitialPermisApresAnnulation'],
						dateAnnulationPermis36DerniersMois: formData['dateAnnulationPermis36DerniersMois'],
						dateSanction36DerniersMois: formData['dateSanction36DerniersMois'],
						dateSuspensionPermis36DerniersMois: formData['dateSuspensionPermis36DerniersMois'],
						dateInfraction36DerniersMois: formData['dateInfraction36DerniersMois'],
						typeSuspensionPermis36DerniersMois: formData['typeSuspensionPermis36DerniersMois'],
						typeSanction: formData['typeSanction'],
						suspensionPermisMotif36DerniersMois: formData['suspensionPermisMotif36DerniersMois'],
						nombreSuspensionPermis36AvecSinistreDerniersMois: formData['nombreSuspensionPermis36AvecSinistreDerniersMois'],
						nombreSuspensionPermis36SansSinistreDerniersMois: formData['nombreSuspensionPermis36SansSinistreDerniersMois'],
						nombreMoisSuspensionPermis36DerniersMois: formData['nombreMoisSuspensionPermis36DerniersMois'],
					},
					dateDernierAlcoolemie36DerniersMois: formData['dateDernierAlcoolemie36DerniersMois'],
					nombreControlesPositifsAlcoolemie36DerniersMois: formData['nombreControlesPositifsAlcoolemie36DerniersMois'],
					isRefusTestAlcoolemie36DerniersMois: formData['isRefusTestAlcoolemie36DerniersMois'],
					isDelitDeFuiteAlcoolemie36DerniersMois: formData['isDelitDeFuiteAlcoolemie36DerniersMois'],
					controleAlcoolemieSuiteA36DerniersMois: formData['controleAlcoolemieSuiteA36DerniersMois'],
					controleAlcoolemieMethode36DerniersMois: formData['controleAlcoolemieMethode36DerniersMois'],
					tauxAlcoolemie: formData['tauxAlcoolemie'],
					isAnnulationOuSuspensionPermis36DerniersMois: formData['isAnnulationOuSuspensionPermis36DerniersMois'],
				},
				stupefiant: {
					sanction: {
						typeAnnulationPermis36DerniersMois: formData['typeAnnulationPermis36DerniersMois'],
						typeSanction: formData['typeSanction'],
						annulationPermisMotif36DerniersMois: formData['annulationPermisMotif36DerniersMois'],
						annulationPermisAvecOuSansSinistre36DerniersMois: formData['annulationPermisAvecOuSansSinistre36DerniersMois'],
					},
					dateDernierStupefiant36DerniersMois: formData['dateDernierStupefiant36DerniersMois'],
					nombreControlesPositifsStupefiants36DerniersMois: formData['nombreControlesPositifsStupefiants36DerniersMois'],
					isRefusTestStupefiant36DerniersMois: formData['isRefusTestStupefiant36DerniersMois'],
					isDelitDeFuiteStupefiant36DerniersMois: formData['isDelitDeFuiteStupefiant36DerniersMois'],
					controleStupefiantSuiteA36DerniersMois: formData['controleStupefiantSuiteA36DerniersMois'],
					controleStupefiantMethode36DerniersMois: formData['controleStupefiantMethode36DerniersMois'],
					isAnnulationOuSuspensionPermis36DerniersMois: formData['isAnnulationOuSuspensionPermis36DerniersMois'],
				},
				sinistres36DerniersMois: [
					{
						dateSinistre36DerniersMois: "2019-12-2",
						natureSinistre36DerniersMois: "Materiel responsable 50",
						isPresenceTiersSinistres36DerniersMois: "Oui",
					},
					{
						dateSinistre36DerniersMois: "2020-11-1",
						natureSinistre36DerniersMois: "Corporel responsable",
						isDelitDeFuiteSinistre36DerniersMois: "Non",
						isInterventionForceDeLOrdreSinistres36DerniersMois: "Non",
						poursuiteTribunalPoliceSinistres36DerniersMois: "AUCUN",
						isPresenceTiersSinistres36DerniersMois: "Non",
					},
					{
						dateSinistre36DerniersMois: "2020-11-1",
					},
					{
						dateSinistre36DerniersMois: "2020-11-1",
					},
					{
						dateSinistre36DerniersMois: "2020-11-1",
					},
				],
			},
			dateNaissance: formData['dateNaissance'],
			datePermis: formData['datePermis'],
			civilite: formData['civilite'],
			nom: formData['nom'],
			prenom: formData['prenom'],
			typePermis: formData['typePermis'],
			situationFamiliale: formData['situationFamiliale'],
			profession: formData['profession'],
			adresse: formData['adresse'],
			codePostal: formData['codePostal'],
			ville: formData['ville'],
			tel: formData['tel'],
			email: formData['email'],
		},
		conducteurSecondaire: {
			isConduiteMaroc: formData['isConduiteMaroc'],
			isConduiteTunisie: formData['isConduiteTunisie'],
			isConduiteTurquie: formData['isConduiteTurquie'],
			isConduiteRussie: formData['isConduiteRussie'],
			antecedents: {
				isEteResilie36DerniersMois: 0,
				alcoolemie: {
					sanction: [],
				},
				stupefiant: {
					sanction: [],
				},
				sinistres36DerniersMois: [[], [], [], [], []],
			},
		},
		urlSource: formData['urlSource'],
		deviceType: "D",
		titulaireCarteGrise: formData['titulaireCarteGrise'],
		garantieSouhaiteeConducteurPrincipal: formData['garantieSouhaiteeConducteurPrincipal'],
		isAjouterConducteurSecondaire: formData['isAjouterConducteurSecondaire'],
	};
}
